# Generated by Django 3.1.7 on 2021-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tegami', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
